###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: ib-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: ib-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: ib-redis

    mysql:
      image: mysql:8.0
      container_name: ib-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=app_root_password
        - MYSQL_DATABASE=app_database
        - MYSQL_USER=app_user
        - MYSQL_PASSWORD=app_password
      ports:
        - "8082:3306"

    postgres:
      image: postgres:latest
      container_name: ib-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=app_user
        - POSTGRES_PASSWORD=app_password
        - POSTGRES_DB=app_database

    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - .:/application

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: ib-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: ib-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ib-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
